window.isMobile=!1;if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)){window.isMobile=!0}
window.isSafari=!1;if(/^((?!chrome|android).)*safari/i.test(navigator.userAgent)){window.isSafari=!0}
window.isSafariVersion='';if(window.isSafari){var version=(navigator.appVersion).match(/Version\/(\d+)\.(\d+)\.?(\d+)? Safari/);if(version!==null){window.isSafariVersion=[parseInt(version[1],10),parseInt(version[2],10),parseInt(version[3]||0,10)]}}
window.browserLang=(window.navigator.userLanguage||window.navigator.language).toUpperCase().slice(0,2);window.tildaBrowserLang=window.browserLang;function t_throttle(fn,threshhold,scope){var last;var deferTimer;threshhold||(threshhold=250);return function(){var context=scope||this;var now=+new Date();var args=arguments;if(last&&now<last+threshhold){clearTimeout(deferTimer);deferTimer=setTimeout(function(){last=now;fn.apply(context,args)},threshhold)}else{last=now;fn.apply(context,args)}}}
function t654_showPanel(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t654');if(!container)return;var buttonClose=rec.querySelector('.t654__icon-close');var storageItem=container.getAttribute('data-storage-item');var delta=container.getAttribute('data-storage-delta')*86400;var today=Math.floor(Date.now()/1000);var lastOpen=null;var currentDelta;try{lastOpen=localStorage.getItem(storageItem);currentDelta=today-lastOpen}catch(e){console.log('Your web browser does not support localStorage.')}
if(lastOpen===null||currentDelta>=delta){container.classList.remove('t654_closed')}
buttonClose.addEventListener('click',function(event){container.classList.add('t654_closed');if(delta){try{localStorage.setItem(storageItem,Math.floor(Date.now()/1000))}catch(e){console.log('Your web browser does not support localStorage.')}}
event.preventDefault()});if(window.innerWidth>980){window.addEventListener('scroll',t_throttle(function(){if(container.classList.contains('t654_bottom')&&document.getElementById('tildacopy')&&(window.innerHeight+window.scrollY)>=document.body.offsetHeight-70){container.style.visibility='hidden'}else{var appearOffset=container.getAttribute('data-appearoffset');if(!appearOffset){container.style.visibility='visible'}}}))}}
function t654_setBg(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t654');if(!container)return;if(window.innerWidth>980){if(container.getAttribute('data-bgcolor-setbyscript')==='yes'){container.style.backgroundColor=container.getAttribute('data-bgcolor-rgba')}}else{container.style.backgroundColor=container.getAttribute('data-bgcolor-hex');container.setAttribute('data-bgcolor-setbyscript','yes')}}
function t654_appearMenu(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t654');if(!container)return;if(window.innerWidth>980){var appearOffset=container.getAttribute('data-appearoffset');if(appearOffset){if(appearOffset.indexOf('vh')>-1){appearOffset=Math.floor((window.innerHeight*(parseInt(appearOffset)/100)))}
appearOffset=parseInt(appearOffset,10);if(window.pageYOffset>=appearOffset){if(getComputedStyle(container,null).visibility==='hidden'){if(container.classList.contains('t654_top')){container.style.top='-50px';container.style.visibility='visible';t654__fadeIn(container);t654__animate(container,'top')}else{container.style.bottom='-50px';container.style.visibility='visible';t654__fadeIn(container);t654__animate(container,'bottom')}}}else{container.style.visibility='hidden'}}}}
function t654_changebgopacitymenu(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t654');if(!container)return;if(window.innerWidth>980){var bgColor=container.getAttribute('data-bgcolor-rgba');var bgColorAfterScroll=container.getAttribute('data-bgcolor-rgba-afterscroll');var bgOpacity=container.getAttribute('data-bgopacity');var bgOpacityTwo=container.getAttribute('data-bgopacity-two');var menuShadow=container.getAttribute('data-menushadow');var menuShadowValue=menuShadow;if(menuShadow!=='100'){menuShadowValue='0.'+menuShadow}
if(window.pageYOffset>20){container.style.backgroundColor=bgColorAfterScroll;if(bgOpacityTwo==='0'||menuShadow===' '){container.style.boxShadow='none'}else{container.style.boxShadow='0px 1px 3px rgba(0, 0, 0, '+menuShadowValue+')'}}else{container.style.backgroundColor=bgColor;if(bgOpacity==='0.0'||menuShadow===' '){container.style.boxShadow='none'}else{container.style.boxShadow='0px 1px 3px rgba(0, 0, 0, '+menuShadowValue+')'}}}}
function t654__fadeIn(el){if(el.style.display==='block')return;var opacity=0;el.style.opacity=opacity;el.style.display='block';var timer=setInterval(function(){el.style.opacity=opacity;opacity+=0.1;if(opacity>=1.0){clearInterval(timer);el.style.display=''}},20)}
function t654__animate(element,animate){var duration=200;var start=parseInt(getComputedStyle(element,null)[animate]);var change=0-start;var currentTime=0;var increment=16;function t654__easeInOutCubic(currentTime,start,change){if((currentTime/=duration/2)<1){return change/2*currentTime*currentTime*currentTime+start}else{return change/2*((currentTime-=2)*currentTime*currentTime+2)+start}}
function t654__animateScroll(){currentTime+=increment;element.style[animate]=t654__easeInOutCubic(currentTime,start,change)+'px';if(currentTime<duration){setTimeout(t654__animateScroll,increment)}else{element.style[animate]='0px'}}
t654__animateScroll()}
function t585_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var accordion=rec.querySelectorAll('.t585__accordion')[0];var headers=rec.querySelectorAll('.t585__header');var isLazy=document.getElementById('allrecords').getAttribute('data-tilda-lazy');var accordionScroll;if(accordion){accordionScroll=accordion.getAttribute('data-scroll-to-expanded');accordion=accordion.getAttribute('data-accordion')}else{accordion='false';accordionScroll='false'}
for(var i=0;i<headers.length;i++){headers[i].addEventListener('click',function(){var element=this;var container=element.nextElementSibling;var triggerButton=element.querySelector('.t585__trigger-button');var activeHeight=0;var isAccordionDown=!1;if(triggerButton){var isExpanded=triggerButton.getAttribute('aria-expanded')==='true';triggerButton.setAttribute('aria-expanded',!isExpanded);container.hidden=isExpanded}
if(element.classList.contains('t585__opened')){element.classList.remove('t585__opened');t585_accordionHide(container)}else{if(accordionScroll==='true'&&accordion==='true'){activeHeight=t585__getOldAction(rec);isAccordionDown=t585__getAccordionPosition(headers,element)}
if(accordion==='true')t585_accordionAllHide(headers);element.classList.add('t585__opened');container.style.display='block';var height=container.scrollHeight;container.style.maxHeight='0px';setTimeout(function(){container.style.maxHeight=height+'px';if(accordionScroll==='true'){t585__calcHeight(element,container,activeHeight,isAccordionDown)}},0)}
if(window.lazy==='y'||isLazy==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}})}}
function t585_accordionAllHide(headers){for(var i=0;i<headers.length;i++){var elementHide=headers[i];elementHide.classList.remove('t585__opened');t585_accordionHide(elementHide.nextElementSibling)}}
function t585_accordionHide(container){if(!container.style.maxHeight)container.style.maxHeight=container.scrollHeight+'px';setTimeout(function(){container.style.maxHeight='0px'},0)}
function t585__getOldAction(rec){var activeHeader=rec.querySelector('.t585__opened');var activeHeight=0;if(activeHeader)var activeContainer=activeHeader.nextElementSibling;if(activeContainer)activeHeight=activeContainer.offsetHeight;return activeHeight}
function t585__getAccordionPosition(headers,element){var oldIndex;var newIndex;for(var i=0;i<headers.length;i++){var header=headers[i];if(header.classList.contains('t585__opened'))oldIndex=i;if(header===element)newIndex=i}
return oldIndex<newIndex?!0:!1}
function t585__calcHeight(element,container,activeHeight,isAccordionDown){var windowHeight=window.innerHeight;var windowScroll=window.scrollY;var containerHeight=container.scrollHeight;var accordionHeight=containerHeight+element.offsetHeight;var elementTopOffset=element.getBoundingClientRect().top+windowScroll;var target=isAccordionDown?elementTopOffset-activeHeight:elementTopOffset;var accordionBottomLine=target+accordionHeight;var windowBottomLine=windowScroll+windowHeight;if(target<windowScroll||accordionHeight>windowHeight||accordionBottomLine>windowBottomLine){t585__scroll(target)}}
function t585__scroll(target){var duration=400;var start=(window.pageYOffset||document.documentElement.scrollTop)-(document.documentElement.clientTop||0);var change=target-start;var currentTime=0;var increment=16;document.body.setAttribute('data-scrollable','true');function t585__easeInOutCubic(currentTime){if((currentTime/=duration/2)<1){return change/2*currentTime*currentTime*currentTime+start}else{return change/2*((currentTime-=2)*currentTime*currentTime+2)+start}}
function t585__animateScroll(){currentTime+=increment;window.scrollTo(0,t585__easeInOutCubic(currentTime));if(currentTime<duration){setTimeout(t585__animateScroll,increment)}else{document.body.removeAttribute('data-scrollable')}}
t585__animateScroll()}
function t649_init(recId){t_onFuncLoad('t_card__moveClickOnCard',function(){t_card__moveClickOnCard(recId)});t_onFuncLoad('t_card__addFocusOnTab',function(){t_card__addFocusOnTab(recId)})}
function t594_init(recId){t_onFuncLoad('t_card__moveClickOnCard',function(){t_card__moveClickOnCard(recId)});t_onFuncLoad('t_card__addFocusOnTab',function(){t_card__addFocusOnTab(recId)})}
function t786__init(recid){setTimeout(function(){t_onFuncLoad('t_prod__init',function(){t_prod__init(recid)});t786_initPopup(recid);t786__hoverZoom_init(recid);t786__updateLazyLoad(recid);t786__alignButtons_init(recid);t_onFuncLoad('t_store_addProductQuantityEvents',function(){t786_initProductQuantity(recid)});var event=document.createEvent('HTMLEvents');event.initEvent('twishlist_addbtn',!0,!1);document.body.dispatchEvent(event)},500)}
function t786_initProductQuantity(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var productList=rec.querySelectorAll('.t786__col, .t786__product-full');Array.prototype.forEach.call(productList,function(product){t_store_addProductQuantityEvents(product)})}
function t786__alignButtons_init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;if(!rec.querySelector('[data-buttons-v-align]')){return}
try{t786__alignButtons(recid);if(document.querySelector('.t-records').getAttribute('data-tilda-mode')==='edit'){setInterval(function(){t786__alignButtons(recid)},200)}
window.addEventListener('resize',t_throttle(function(){if(typeof window.noAdaptive!=='undefined'&&window.noAdaptive&&window.isMobile){return}
t786__alignButtons(recid)}));var wrapperBlock=rec.querySelector('.t786');if(wrapperBlock){wrapperBlock.addEventListener('displayChanged',function(){t786__alignButtons(recid)})}
if(window.isMobile){window.addEventListener('orientationchange',function(){t786__alignButtons(recid)})}}catch(error){console.log('buttons-v-align error: '+error.message)}}
function t786__showMore(recid){var rec=document.querySelector('#rec'+recid+' .t786');if(!rec)return;var cardsShowLimit=parseInt(rec.getAttribute('data-show-count'),10);if(isNaN(cardsShowLimit)||cardsShowLimit<=0)return;var showMoreButton=rec.querySelector('.t786__showmore');if(!showMoreButton)return;if(!showMoreButton.querySelector('td').textContent){showMoreButton.querySelector('td').textContent=t786__dict()}
showMoreButton.style.display='inline-block';var allProductCards=rec.querySelectorAll('.t786__col');Array.prototype.forEach.call(allProductCards,function(productCard){productCard.style.display='none'});var cardsNumber=allProductCards.length;t786__showSeparator(rec,cardsShowLimit);for(var i=0;i<cardsShowLimit;i++){if(allProductCards[i]){allProductCards[i].style.display='inline-block'}}
showMoreButton.addEventListener('click',function(){var allCurrentProducts=rec.querySelectorAll('.t786__col');var currentproductsShowed=0;Array.prototype.forEach.call(allCurrentProducts,function(product){if(product.style.display==='inline-block'){++currentproductsShowed}});for(var i=0;i<cardsShowLimit+currentproductsShowed;i++){if(allProductCards[i]){allProductCards[i].style.display='inline-block'}}
if(rec.querySelector('[data-buttons-v-align]')){t786__alignButtons(recid)}
var displayChangedEvent=document.createEvent('HTMLEvents');displayChangedEvent.initEvent('displayChanged',!0,!1);rec.dispatchEvent(displayChangedEvent);var addBtnEvent=document.createEvent('HTMLEvents');addBtnEvent.initEvent('twishlist_addbtn',!0,!1);document.body.dispatchEvent(addBtnEvent);if(cardsShowLimit+currentproductsShowed>=cardsNumber){showMoreButton.style.display='none'}
t786__showSeparator(rec,cardsShowLimit+currentproductsShowed);if(rec.querySelector('[data-buttons-v-align]')){t786__alignButtons(recid)}
if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}})}
function t786__dict(){var dictionary={EN:'Load more',RU:'Загрузить ещё',FR:'Charger plus',DE:'Mehr laden',ES:'Carga más',PT:'Carregue mais',UK:'Завантажити ще',JA:'もっと読み込む',ZH:'裝載更多',};var language=window.browserLang;return dictionary[language]?dictionary[language]:dictionary.EN}
function t786__showSeparator(rec,cardsShowLimit){if(window.jQuery&&rec instanceof jQuery){rec=rec.get(0)}
var allSeparators=rec.querySelectorAll('.t786__separator_number');Array.prototype.forEach.call(allSeparators,function(separator){separator.classList.add('t786__separator_hide');if(separator.getAttribute('data-product-separator-number')<=cardsShowLimit){separator.classList.remove('t786__separator_hide')}})}
function t786__alignButtons(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var wrappers=rec.querySelectorAll('.t786__textwrapper');var maxHeight=0;var container=rec.querySelector('.t786__container');if(container){var itemsInRow=parseInt(container.getAttribute('data-blocks-per-row'),10)}else{itemsInRow=1}
var mobileView=window.innerWidth<=480;var tableView=window.innerWidth<=960&&window.innerWidth>480;var mobileOneRow=window.innerWidth<=960&&rec.querySelector('.t786__container_mobile-flex');var mobileTwoItemsInRow=window.innerWidth<=480&&rec.querySelector('.t786 .mobile-two-columns');if(mobileView){itemsInRow=1}
if(tableView){itemsInRow=2}
if(mobileTwoItemsInRow){itemsInRow=2}
if(mobileOneRow){itemsInRow=999999}
var count=1;var wrappersInRow=[];Array.prototype.forEach.call(wrappers,function(wrapper){wrapper.style.height='auto';if(itemsInRow===1){wrapper.style.height='auto'}else{wrappersInRow.push(wrapper);if(wrapper.offsetHeight>maxHeight){maxHeight=wrapper.offsetHeight}
Array.prototype.forEach.call(wrappersInRow,function(card){card.style.height=maxHeight+'px'});if(count===itemsInRow){count=0;maxHeight=0;wrappersInRow=[]}
count++}})}
function t786__hoverZoom_init(recid){if(window.isMobile)return;var rec=document.getElementById('rec'+recid);if(!rec)return;try{if(!rec.querySelector('[data-hover-zoom]')){return}
var hoverScript='https://static.tildacdn.com/js/tilda-hover-zoom-1.0.min.js';if(document.querySelector("script[src^='"+hoverScript+"']")){t_onFuncLoad('t_hoverZoom_init',function(){t_hoverZoom_init(recid)})}else{var script=document.createElement('script');script.type='text/javascript';script.src=hoverScript;script.onload=function(){setTimeout(function(){t_hoverZoom_init(recid)},500)};script.onerror=function(error){console.log('Upload script error: ',error)};document.head.appendChild(script)}}catch(error){console.log('Zoom image init error: '+error.message)}}
function t786__updateLazyLoad(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var scrollContainer=rec.querySelector(' .t786__container_mobile-flex');var currentMode=document.querySelector('.t-records').getAttribute('data-tilda-mode');if(scrollContainer&&currentMode!=='edit'&&currentMode!=='preview'){scrollContainer.addEventListener('scroll',t_throttle(function(){if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}))}}
function t786_initPopup(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var openerLink=rec.querySelectorAll('[href^="#prodpopup"]');Array.prototype.forEach.call(openerLink,function(link){link.addEventListener('click',clickOnceHandler,!1);function clickOnceHandler(event){event.preventDefault();var product=link.closest('.js-product');var productLid=product.getAttribute('data-product-lid');t_onFuncLoad('t_sldsInit',function(){t_sldsInit(recid+' #t786__product-'+productLid+'')});link.removeEventListener('click',clickOnceHandler,!1)}
link.addEventListener('click',showPopupHandler,!1);function showPopupHandler(event){event.preventDefault();if(event.target.classList.contains('t1002__addBtn')||event.target.parentNode.classList.contains('t1002__addBtn')){return}
t786_showPopup(recid);var popup=rec.querySelector('.t-popup');var product=link.closest('.js-product');var productLid=product.getAttribute('data-product-lid');var allProducts=popup.querySelectorAll('.js-product');Array.prototype.forEach.call(allProducts,function(product){product.style.display='none'});var productFull=popup.querySelector('.js-product[data-product-lid="'+productLid+'"]');productFull.style.display='block';var analitics=popup.getAttribute('data-track-popup');if(analitics&&productFull&&window.Tilda){var productName=productFull.querySelector('.js-product-name');if(productName){var virtualTitle=productName.textContent;if(!virtualTitle){virtualTitle='prod'+productLid}
Tilda.sendEventToStatistics(analitics,virtualTitle)}}
var currentUrl=window.location.href;if(currentUrl.indexOf('#!/tproduct/')===-1&&currentUrl.indexOf('%23!/tproduct/')===-1){if(typeof history.replaceState!=='undefined'){window.history.replaceState('','',window.location.href+'#!/tproduct/'+recid+'-'+productLid)}}
t786_updateSlider(recid+' #t786__product-'+productLid);if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}});if(document.querySelectorAll('#record'+recid).length===0){t786_checkUrl(recid)}
t786_copyTypography(recid)}
function t786_checkUrl(recid){var currentUrl=window.location.href;var tprodIndex=(currentUrl.indexOf('#!/tproduct/')+1||currentUrl.indexOf('%23!/tproduct/')+1||currentUrl.indexOf('#%21%2Ftproduct%2F')+1||currentUrl.indexOf('#!%2Ftproduct%2F')+1||currentUrl.indexOf('%23%21%2Ftproduct%2F')+1)-1;if(tprodIndex!==-1){var currentUrl=currentUrl.substring(tprodIndex,currentUrl.length);var curProdLid=currentUrl.substring(currentUrl.indexOf('-')+1,currentUrl.length);if(curProdLid){var curProdLidMatch=curProdLid.match(/([0-9]+)/g);if(curProdLidMatch){curProdLid=curProdLidMatch[0]}}
if(currentUrl.indexOf(recid)===-1)return;var rec=document.getElementById('rec'+recid);if(!rec)return;if(currentUrl.indexOf(recid)!==0&&rec.querySelector('[data-product-lid="'+curProdLid+'"]')){var currentLink=rec.querySelector('[data-product-lid="'+curProdLid+'"] [href^="#prodpopup"]');var event=document.createEvent('HTMLEvents');event.initEvent('click',!0,!1);if(currentLink){currentLink.dispatchEvent(event)}}}}
function t786_updateSlider(recid){var rec=document.querySelector('#rec'+recid);if(!rec)return;t_onFuncLoad('t_slds_SliderWidth',function(){t_slds_SliderWidth(recid)});var slider=rec.querySelector('.t-slds__container');var paddingLeft=parseInt(slider.style.paddingLeft)||0;var paddingRight=parseInt(slider.style.paddingRight)||0;var sliderWrapper=rec.querySelector('.t-slds__items-wrapper');var sliderWidth=slider.clientWidth-(paddingLeft+paddingRight);var position=parseFloat(sliderWrapper.getAttribute('data-slider-pos'));sliderWrapper.style.transform='translate3d(-'+sliderWidth*position+'px, 0, 0)';t_onFuncLoad('t_slds_UpdateSliderHeight',function(){t_slds_UpdateSliderHeight(recid)});t_onFuncLoad('t_slds_UpdateSliderArrowsHeight',function(){t_slds_UpdateSliderArrowsHeight(recid)})}
function t786_showPopup(recid){var rec=document.querySelector('#rec'+recid);if(!rec)return;var popup=rec.querySelector('.t-popup');popup.style.display='block';setTimeout(function(){popup.querySelector('.t-popup__container').classList.add('t-popup__container-animated');popup.classList.add('t-popup_show')},50);setTimeout(function(){if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}},300);var body=document.body;if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupShowed');body.classList.add('t-body_popupshowed');var event=document.createEvent('HTMLEvents');event.initEvent('twishlist_addbtn',!0,!1);body.dispatchEvent(event);popup.addEventListener('mousedown',function(event){var windowWidth=window.innerWidth;var maxScrollBarWidth=17;var windowWithoutScrollBar=windowWidth-maxScrollBarWidth;if(event.clientX>windowWithoutScrollBar){return}
if(event.target===this){t786_closePopup(body,popup)}});var closeButtons=rec.querySelectorAll('.t-popup__close, .t786__close-text');Array.prototype.forEach.call(closeButtons,function(button){button.addEventListener('click',function(){t786_closePopup(body,popup)})});document.addEventListener('keydown',function(event){var isGalleryShowedOldLib=document.body.classList.contains('t-zoomer__show');if(isGalleryShowedOldLib)return;var isGalleryShowedNewLib=document.body.classList.contains('t-zoomer__active');if(isGalleryShowedNewLib)return;var isPopupShowed=document.body.classList.contains('t-body_popupshowed');if(!isPopupShowed)return;if(popup&&popup.classList.contains('t-popup_show')){if(event.keyCode===27){t786_closePopup(body,popup)}}})}
function t786_closePopup(body,popup){if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupHidden');body.classList.remove('t-body_popupshowed');popup.classList.remove('t-popup_show');var event=document.createEvent('HTMLEvents');event.initEvent('twishlist_addbtn',!0,!1);body.dispatchEvent(event);var currentUrl=window.location.href;var indexToRemove=currentUrl.indexOf('#!/tproduct/');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&indexToRemove<0){indexToRemove=currentUrl.indexOf('%23!/tproduct/')}
currentUrl=currentUrl.substring(0,indexToRemove);setTimeout(function(){popup.scrollTop=0;popup.style.display='none';if(typeof history.replaceState!=='undefined'){window.history.replaceState('','',currentUrl)}},300)}
function t786_removeSizeStyles(styleStr){if(styleStr&&(styleStr.indexOf('font-size')!==-1||styleStr.indexOf('padding-top')!==-1||styleStr.indexOf('padding-bottom')!==-1)){var styleStrSplitted=styleStr.split(';');styleStr='';for(var i=0;i<styleStrSplitted.length;i++){if(styleStrSplitted[i].indexOf('font-size')!==-1||styleStrSplitted[i].indexOf('padding-top')!==-1||styleStrSplitted[i].indexOf('padding-bottom')!==-1){styleStrSplitted.splice(i,1);i--;continue}
if(styleStrSplitted[i]===''){continue}
styleStr+=styleStrSplitted[i]+';'}}
return styleStr}
function t786_copyTypography(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var productTitle=rec.querySelector('.t786__title');var productDescription=rec.querySelector('.t786__descr');if(productTitle)var titleStyle=productTitle.getAttribute('style');if(productDescription)var descriptionStyle=productDescription.getAttribute('style');var popupTitles=rec.querySelectorAll('.t-popup .t786__title');Array.prototype.forEach.call(popupTitles,function(title){title.setAttribute('style',t786_removeSizeStyles(titleStyle?titleStyle:''))});var popupDescription=rec.querySelectorAll('.t-popup .t786__descr, .t-popup .t786__text');Array.prototype.forEach.call(popupDescription,function(description){description.setAttribute('style',t786_removeSizeStyles(descriptionStyle?descriptionStyle:''))})}
if(!Element.prototype.matches){Element.prototype.matches=Element.prototype.matchesSelector||Element.prototype.msMatchesSelector||Element.prototype.mozMatchesSelector||Element.prototype.webkitMatchesSelector||Element.prototype.oMatchesSelector}
if(!Element.prototype.closest){Element.prototype.closest=function(s){var el=this;while(el&&el.nodeType===1){if(Element.prototype.matches.call(el,s)){return el}
el=el.parentElement||el.parentNode}
return null}}
function t450_showMenu(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menu=rec.querySelector('.t450');var overlay=rec.querySelector('.t450__overlay');var menuElements=rec.querySelectorAll('.t450__overlay, .t450__close, a[href*="#"]');if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupShowed');document.body.classList.add('t450__body_menushowed');if(menu)menu.classList.add('t450__menu_show');if(overlay)overlay.classList.add('t450__menu_show');if(menu){menu.addEventListener('clickedAnchorInTooltipMenu',function(){t450_closeMenu(menu,overlay)})}
Array.prototype.forEach.call(menuElements,function(element){element.addEventListener('click',function(){if(element.closest('.tooltipstered, .t-menusub__target-link, .t794__tm-link, .t966__tm-link, .t978__tm-link'))return;if(element.href&&(element.href.substring(0,7)==='#price:'||element.href.substring(0,9)==='#submenu:'))return;t450_closeMenu(menu,overlay)})});document.addEventListener('keydown',function(e){if(e.keyCode===27){document.body.classList.remove('t390__body_popupshowed');var popups=document.querySelectorAll('.t390');Array.prototype.forEach.call(popups,function(popup){popup.classList.remove('t390__popup_show')})}});rec.addEventListener('click',function(e){if(e.target.closest('.t966__tm-link, .t978__tm-link')){t450_checkSize(recid);if(e.target.closest('.t978__tm-link')){setTimeout(function(){var hookLink=e.target.closest('.t978__tm-link');var menuBlock=hookLink.nextElementSibling;var submenuLinks=menuBlock?menuBlock.querySelectorAll('.t978__menu-link'):[];Array.prototype.forEach.call(submenuLinks,function(link){link.addEventListener('click',function(){t450_checkSize(recid)})})},300)}}});menu.addEventListener('menuOverflow',function(){t450_checkSize(recid)});t450_highlight(recid)}
function t450_closeMenu(menu,overlay){if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupHidden');document.body.classList.remove('t450__body_menushowed');if(menu)menu.classList.remove('t450__menu_show');if(overlay)overlay.classList.remove('t450__menu_show')}
function t450_checkSize(recid){var rec=document.getElementById('rec'+recid);var menu=rec?rec.querySelector('.t450'):null;if(!menu)return;var container=menu.querySelector('.t450__container');var topContainer=menu.querySelector('.t450__top');var rightContainer=menu.querySelector('.t450__rightside');setTimeout(function(){var topContainerHeight=topContainer?topContainer.offsetHeight:0;var rightContainerHeight=rightContainer?rightContainer.offsetHeight:0;var containerPaddingTop=container?window.getComputedStyle(container).paddingTop:'0';var containerPaddingBottom=container?window.getComputedStyle(container).paddingBottom:'0';containerPaddingTop=parseInt(containerPaddingTop,10);containerPaddingBottom=parseInt(containerPaddingBottom,10);if(topContainerHeight+rightContainerHeight+containerPaddingTop+containerPaddingBottom>document.documentElement.clientHeight){menu.classList.add('t450__overflowed')}else{menu.classList.remove('t450__overflowed')}})}
function t450_appearMenu(recid){var rec=document.getElementById('rec'+recid);var burger=rec?rec.querySelector('.t450__menu__content'):null;if(!burger)return;var burgerAppearOffset=burger?burger.getAttribute('data-appearoffset'):'';var burgerHideOffset=burger?burger.getAttribute('data-hideoffset'):'';if(burgerAppearOffset){burgerAppearOffset=t450_appearMenuParseNumber(burgerAppearOffset);if(window.pageYOffset>=burgerAppearOffset){if(burger.classList.contains('t450__beforeready')){burger.classList.remove('t450__beforeready')}}else{burger.classList.add('t450__beforeready')}}
if(burgerHideOffset){burgerHideOffset=t450_appearMenuParseNumber(burgerHideOffset);var scrollHeight=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);if(window.pageYOffset+window.innerHeight>=scrollHeight-burgerHideOffset){if(!burger.classList.contains('t450__beforeready')){burger.classList.add('t450__beforeready')}}else if(burgerAppearOffset){if(window.pageYOffset>=burgerAppearOffset){burger.classList.remove('t450__beforeready')}}else{burger.classList.remove('t450__beforeready')}}}
function t450_appearMenuParseNumber(string){if(string.indexOf('vh')>-1){string=Math.floor((window.innerHeight*(parseInt(string)/100)))}
return parseInt(string,10)}
function t450_initMenu(recid){var rec=document.getElementById('rec'+recid);var menu=rec?rec.querySelector('.t450'):null;var overlay=rec?rec.querySelector('.t450__overlay'):null;var burger=rec?rec.querySelector('.t450__burger_container'):null;var menuLinks=rec?rec.querySelectorAll('.t-menu__link-item.t450__link-item_submenu'):[];var hook=menu?menu.getAttribute('data-tooltip-hook'):'';if(hook){document.addEventListener('click',function(e){if(e.target.closest('a[href="'+hook+'"]')){e.preventDefault();t450_closeMenu(menu,overlay);t450_showMenu(recid);t450_checkSize(recid)}})}
if(burger){burger.addEventListener('click',function(){t450_closeMenu(menu,overlay);t450_showMenu(recid);t450_checkSize(recid)})}
window.addEventListener('resize',function(){t450_checkSize(recid)});if(!window.isMobile)return;Array.prototype.forEach.call(menuLinks,function(link){link.addEventListener('click',function(){t450_checkSize(recid)})})}
function t450_highlight(recid){var url=window.location.href;var pathname=window.location.pathname;var hash=window.location.hash;if(url.substr(url.length-1)==='/'){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)==='/'){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)==='/'){pathname=pathname.slice(1)}
if(pathname===''){pathname='/'}
var shouldBeActiveElements=document.querySelectorAll('.t450__menu a[href=\''+url+'\'], '+'.t450__menu a[href=\''+url+'/\'], '+'.t450__menu a[href=\''+pathname+'\'], '+'.t450__menu a[href=\'/'+pathname+'\'], '+'.t450__menu a[href=\''+pathname+'/\'], '+'.t450__menu a[href=\'/'+pathname+'/\']'+(hash?', .t450__menu a[href=\''+hash+'\']':''));var rec=document.getElementById('rec'+recid);var menuLinks=rec?rec.querySelectorAll('.t450__menu a'):[];Array.prototype.forEach.call(menuLinks,function(link){if(link.getAttribute('data-highlighted-by-user')!=='y')link.classList.remove('t-active')});Array.prototype.forEach.call(shouldBeActiveElements,function(link){link.classList.add('t-active')})}
window.requestAnimationFrame=(function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(callback){window.setTimeout(callback,1000/60)}})();function t270_scroll(hash,offset){if(!hash)return;t270_checkLoad(hash,offset);if(hash.indexOf('#!/tproduct/')!==-1||hash.indexOf('#!/tab/')!==-1){return!0}
var isHistoryChangeAllowed=window.location.hash!==hash;var wrapperBlock=document.querySelector('.t270');var dontChangeHistory=wrapperBlock?Boolean(wrapperBlock.getAttribute('data-history-disabled')):!1;t270_scrollToEl(hash,offset);if(!dontChangeHistory&&isHistoryChangeAllowed){if(history.pushState){history.pushState(null,null,hash)}else{window.location.hash=hash}
isHistoryChangeAllowed=!1}
return!0}
function t270_checkLoad(hash,offset){if(window.t270_loadChecked)return;var sliderWrappers=document.body.querySelectorAll('.t-slds__items-wrapper');if(!sliderWrappers.length)return;var lastWrapper=sliderWrappers[sliderWrappers.length-1];var sliderImgs=lastWrapper?lastWrapper.querySelectorAll('.t-slds__bgimg'):[];var lastImg=sliderImgs[sliderImgs.length-1];var imageUrl=lastImg?window.getComputedStyle(lastImg).backgroundImage:'';imageUrl=imageUrl.substring(5,imageUrl.length-2);var preloaderImg=document.createElement('img');preloaderImg.src=imageUrl?imageUrl:'';preloaderImg.addEventListener('load',function(){t270_scroll(hash,offset);window.t270_loadChecked=!0})}
function t270_scrollToEl(hash,offset){if(document.body.getAttribute('data-scroll'))return;var scrollTargetY=t270_getTarget(hash,offset);if(isNaN(scrollTargetY))return;var html=document.querySelector('html');var body=document.body;var documentHeight=Math.max(body.scrollHeight,body.offsetHeight,body.clientHeight,html.offsetHeight);var scrollY=window.scrollY||document.documentElement.scrollTop;var speed=2000;var time=Math.max(.1,Math.min(Math.abs(scrollY-scrollTargetY)/speed,.8));var currentTime=0;function t270_easeInQuad(pos){return Math.pow(pos,2)}
function t270_animationScroll(){currentTime+=1/60;var newDocumentHeight=Math.max(body.scrollHeight,body.offsetHeight,body.clientHeight,html.offsetHeight);if(documentHeight<newDocumentHeight){documentHeight=newDocumentHeight;scrollTargetY=t270_getTarget(hash,offset);scrollY=window.scrollY||document.documentElement.scrollTop;time=Math.max(.1,Math.min(Math.abs(scrollY-scrollTargetY)/speed,.8))}
var difference=currentTime/time;var animation=t270_easeInQuad(difference);if(difference<1){requestAnimationFrame(t270_animationScroll);window.scrollTo(0,scrollY+((scrollTargetY-scrollY)*animation))}else{body.removeAttribute('data-scroll');body.removeAttribute('data-scrollable');window.scrollTo(0,scrollTargetY)}}
body.setAttribute('data-scroll','true');body.setAttribute('data-scrollable','true');t270_animationScroll()}
function t270_getTarget(hash,offset){var target;try{if(hash.substring(0,1)==='#'){target=document.getElementById(hash.substring(1))}else{target=document.querySelector(hash)}}catch(event){console.log('Exception t270: '+event.message);return}
if(!target){target=document.querySelector('a[name="'+hash.substr(1)+'"]');if(!target)return}
target=parseInt((target.getBoundingClientRect().top+window.pageYOffset)-offset,10);target=Math.max(target,0);return target}